image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - sleep 20
  - ps: netstat -tulpn | grep LISTEN

  # запускаем SUT (запоминаем информацию о процессе в переменной $App)

test_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)

on_finish:
  - ps: Stop-Process -Id $App.Id  # оставливаем SUT