version: '3'
services:
  #  http:
  #    image: nginx:latest
  #    ports:
  #      - 8080:80
  #    volumes:
  #      - ./html:/usr/share/nginx/html:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  MySQL:
    image: mysql:8.0.18
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: Password12
      MYSQL_DATABASE: app

  Postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password12
      POSTGRES_DB: root

volumes:
  pgdata: